const stages=new Set();
function track(name,detail={}){if(stages.has(name))return;stages.add(name);if(typeof gtag==='function')gtag('event',name,{event_category:'dev_quiz',app_language:window.i18n?.getCurrentLanguage?.()||'en',...detail})}
class DevQuiz{
 constructor(){this.index=0;this.correct=0;this.answered=false;this.q=window.DEV_QUESTIONS;this.bind();track('dev_quiz_view')}
 bind(){document.getElementById('start').addEventListener('click',()=>this.start());document.getElementById('next').addEventListener('click',()=>this.next());document.getElementById('retry').addEventListener('click',()=>this.start());document.getElementById('share').addEventListener('click',()=>this.share());document.querySelectorAll('[data-target-slug]').forEach(a=>a.addEventListener('click',()=>track('dev_quiz_related_click',{target_slug:a.dataset.targetSlug})));document.addEventListener('devquiz:language',()=>{if(document.getElementById('quiz').classList.contains('active'))this.render();if(document.getElementById('result').classList.contains('active'))this.renderResult()})}
 show(id){document.querySelectorAll('.screen').forEach(s=>s.classList.toggle('active',s.id===id))}
 start(){this.index=0;this.correct=0;this.answered=false;this.show('quiz');this.render();track('dev_quiz_start')}
 render(){const item=this.q[this.index],total=this.q.length;document.getElementById('progress-label').textContent=i18n.format('quiz.progress',{current:this.index+1,total});document.getElementById('category').textContent=item.category;document.getElementById('bar').style.width=`${((this.index+1)/total)*100}%`;document.getElementById('question-title').textContent=i18n.t('quiz.choose');document.getElementById('snippet').textContent=item.code;const choices=document.getElementById('choices');choices.replaceChildren();item.choices.forEach((text,index)=>{const button=document.createElement('button');button.className='choice';button.textContent=text;button.addEventListener('click',()=>this.answer(index));choices.append(button)});document.getElementById('feedback').textContent='';document.getElementById('feedback').className='feedback';document.getElementById('next').classList.add('hidden');this.answered=false;requestAnimationFrame(()=>document.getElementById('question-title').focus())}
 answer(choice){if(this.answered)return;this.answered=true;const item=this.q[this.index],buttons=[...document.querySelectorAll('.choice')];buttons.forEach((button,index)=>{button.disabled=true;if(index===item.answer)button.classList.add('correct');else if(index===choice)button.classList.add('wrong')});if(choice===item.answer)this.correct++;const feedback=document.getElementById('feedback');feedback.textContent=choice===item.answer?i18n.t('quiz.correct'):i18n.format('quiz.incorrect',{answer:item.choices[item.answer]});feedback.classList.add(choice===item.answer?'ok':'no');const next=document.getElementById('next');next.textContent=i18n.t(this.index===this.q.length-1?'quiz.finish':'quiz.next');next.classList.remove('hidden')}
 next(){if(!this.answered)return;if(++this.index<this.q.length)this.render();else this.complete()}
 complete(){this.show('result');this.renderResult();track('dev_quiz_complete');const reveal=()=>{};if(typeof GameAds!=='undefined')GameAds.showInterstitial({onComplete:reveal})}
 renderResult(){document.getElementById('result-count').textContent=i18n.format('result.summary',{correct:this.correct,total:this.q.length})}
 async share(){const lang=i18n.getCurrentLanguage(),url=`https://dopabrain.com/dev-quiz/?lang=${lang}`;try{if(navigator.share)await navigator.share({title:'Developer Quiz',text:i18n.t('share.text'),url});else if(navigator.clipboard?.writeText)await navigator.clipboard.writeText(url);else throw Error('share unavailable');track('dev_quiz_share');const button=document.getElementById('share'),original=button.textContent;button.textContent=i18n.t('share.copied');setTimeout(()=>button.textContent=original,1500)}catch(error){if(error?.name!=='AbortError')console.warn('Share failed:',error?.message||error)}}
}
window.addEventListener('load',async()=>{await i18n.init();window.devQuiz=new DevQuiz();document.getElementById('app-loader')?.remove();if(typeof GameAds!=='undefined')GameAds.init();if('serviceWorker'in navigator)navigator.serviceWorker.register('/dev-quiz/sw.js',{scope:'/dev-quiz/'}).catch(()=>{})});
